INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10100,'2013-05-02','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10101,'2014-11-30','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10102,'2011-02-03','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10103,'2011-11-23','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10104,'2013-05-02','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10105,'2011-12-03','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10106,'2014-01-22','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10107,'2013-01-13','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10108,'2011-01-27','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10109,'2013-08-20','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10110,'2012-03-09','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10111,'2013-05-10','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10112,'2011-07-07','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10113,'2014-10-05','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10114,'2015-06-11','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10115,'2015-10-21','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10116,'2012-01-15','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10117,'2013-05-17','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10118,'2014-09-06','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10119,'2015-03-03','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10120,'2013-05-02','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10121,'2013-06-06','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10122,'2013-03-16','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10123,'2013-06-04','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10124,'2014-07-14','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10125,'2015-02-06','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10126,'2013-06-27','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10127,'2013-10-06','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10128,'2015-08-31','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10129,'2015-04-04','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10130,'2014-11-30','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10131,'2015-05-07','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10132,'2012-11-28','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10133,'2015-07-01','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10134,'2013-04-05','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10135,'2012-01-22','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10136,'2015-08-21','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10137,'2013-09-07','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10138,'2013-06-10','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10139,'2015-10-05','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10140,'2012-01-19','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10141,'2011-08-08','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10142,'2014-03-20','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10143,'2014-11-28','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10144,'2011-12-20','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10145,'2014-02-09','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10146,'2011-12-20','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10147,'2011-07-28','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10148,'2011-09-10','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10149,'2015-01-07','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10150,'2015-06-02','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10151,'2015-09-28','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10152,'2012-09-24','Fixed Deposit',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10153,'2013-09-26','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10154,'2013-03-08','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10155,'2012-01-27','Corporate',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10156,'2014-10-22','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10157,'2014-08-11','Personal Current',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10158,'2012-12-30','Personal Savings',5);
INSERT into [dbo].[Dim_Account] ([_Source Key], [Account Open Date], [Account Type], [Lineage Key]) VALUES (10159,'2013-03-13','Fixed Deposit',5);
