USE [BankOne_DW]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Account](
	[Account Key] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[_Source Key] NVARCHAR(50) NOT NULL,
	[Account Open Date] DATE NOT NULL,
	[Account Type] NVARCHAR(50) NOT NULL,
	[Lineage Key] INT NOT NULL
)